#!/bin/bash

difftool="$1"
path="$2"
oldfile="$3"
oldhex="$4"
oldmode="$5"
newfile="$6"
newhex="$7"
newmode="$8"

esc=$(printf '\033[')
msg="${esc}1m*** $path${esc}m"
if [ "$#" == "1" ]; then
    echo "$msg: unmerged"
else
    if [ "$oldfile" == "/dev/null" ]; then
        echo "$msg: new file, mode $newmode"
        echo
    else
        echo "$msg: file changed"
        echo
        if [ "$oldmode" != "$newmode" ]; then
            echo "mode change: $oldmode -> $newmode"
            echo
        fi
    fi
    "$difftool" "$oldfile" "$newfile"
    echo
fi
