#!/bin/sh

# Ignore all flags
while getopts uL: flag; do true; done
shift $(($OPTIND - 1))

esc=$(printf '\033[')
wdiff -n -w "${esc}97;41m" -x "${esc}m" -y "${esc}97;44m" -z "${esc}m" "$@" | fgrep -C2 "$esc"
exec cmp -s "$@"
