#!/bin/bash

# Ignore all flags
while getopts uL: flag; do true; done
shift $(($OPTIND - 1))

esc=$(printf '\033[')
wdiff -n -w "${esc}1;31m" -x "${esc}m" -y "${esc}1;34m" -z "${esc}m" "$@" | fgrep -C2 "$esc"
exec cmp -s "$@"
